services:

  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "10000:3306"
    command: >
      mysqld
      --sql_mode=""
      --character-set-server=utf8
      --collation-server=utf8_slovenian_ci
      --init-connect='SET NAMES UTF8;'
      --innodb-flush-log-at-trx-commit=0
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./dump:/docker-entrypoint-initdb.d:ro
      - ./conf:/etc/mysql/conf.d:ro
      - persistent:/var/lib/mysql
    networks:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p:wordpress"]
      interval: 10s
      timeout: 5s
      retries: 5


  wordpress:
    depends_on:
      - db 
    image: wordpress:latest
    ports: 
      - '10001:80'
    restart: always
    environment: 
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks: 
      - frontend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "10002:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db
    networks:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true

volumes:
  persistent:
