services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./dump:/docker-entrypoint-initdb.d:ro
      - ./conf:/etc/mysql/conf.d:ro
      - persistent:/var/lib/mysql
    networks:
      - frontend
      - backend
  web:
        image: wordpress:latest
        depends_on:
            - db
        volumes:
            - ./target:/var/www/html
        environment:
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
        ports:
            - "${HOST}:80"
        networks:
            - frontend
            - backend
  phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: unless-stopped
        ports:
          - "${PHPMYADMIN_PORT}:80"
        environment:
          PMA_HOST: db
          PMA_USER: ${MYSQL_USER}
          PMA_PASSWORD: ${MYSQL_PASSWORD}
          UPLOAD_LIMIT: ${PHP_UPLOAD_MAX_FILESIZE}
        depends_on:
          - db
        networks:
          - frontend
          - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true
volumes:
  persistent:
  data:
